name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Tools
      run: sudo apt-get install gawk wget python git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm

    - name: Git buildroot
      run: cd ~; git clone https://github.com/vowstar/k210-linux-nommu.git
    
    - name: Configure
      run: cd ~; cd k210-linux-nommu;export PROJ_ROOT=$(pwd);cd $PROJ_ROOT;sh ./prepare_buildroot.sh;
      
    - name: Build
      run: cd "~/k210-linux-nommu/riscv64-nommu-buildroot";make riscv64_nommu_defconfig;make;
      
    - name: Compress
      run: cd "~/k210-linux-nommu/riscv64-nommu-buildroot";tar -czvf toolchain.tar.gz output/host
      
    - uses: actions/upload-artifact@v3
      with:
          name: my-artifact
          path: ~/k210-linux-nommu/riscv64-nommu-buildroot/toolchain.tar.gz

